# 이름 : application-local.yml

security:
  permit-all:
    urls:
      - "/auth/**"
      - "/v3/api/test1"
      - "/ws-stomp/**"
      - "/suspends"
      - "/login/oauth2/code/**"
      # --- Swagger / Springdoc ---
      - "/swagger-ui/**"
      - "/v3/api-docs/**"
      - "/swagger-resources/**"
      - "/webjars/**"
      # --- 정적/루트/헬스체크 ---
      - "/"
      - "/favicon.ico"
      - "/.well-known/**"
      - "/actuator/health"
      # Sse 구독 엔드포인트 허용
      - "/subscribe/**"
