spring:
  application:
    name: codin-ticketing-sse
  config:
    import: optional:file:./.env[.properties], optional:file:./.env.local[.properties]
  # Redis Configuration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6380}
      password: ${REDIS_PASSWORD:1234}
      database: ${REDIS_DATABASE:0}

server:
  domain: https://codin.inu.ac.kr
  forward-headers-strategy: framework
  port: ${SSE_SERVER_PORT:8082}
