spring:
  application:
    name: codin-ticketing-sse
  jwt:
    secret: ${SPRING_JWT_SECRET}
  mvc:
    async:
      request-timeout: 0
  config:
    import: optional:file:./.env[.properties], optional:file:./.env.local[.properties]
  # Redis Configuration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6380}
      password: ${REDIS_PASSWORD:1234}
      database: ${REDIS_DATABASE:0}

# Redis Stream Configuration
redis:
  stream:
    stock:
      key: ${STOCK_REDIS_STREAM_KEY:event-stock-stream}
      group: ${STOCK_REDIS_STREAM_GROUP:event-stock-group}
      consumer: ${STOCK_REDIS_STREAM_CONSUMER:event-stock-consumer}

server:
  domain: https://codin.inu.ac.kr
  forward-headers-strategy: framework
  port: ${SSE_SERVER_PORT:8084}

# Swagger SpringDoc Configuration
springdoc:
  override-with-generic-response: false
  api-docs:
    enabled: true
  swagger-ui:
    groups-order: DESC
    doc-expansion: list
    tags-sorter: alpha
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true

# Hibernate Log Level Configuration
logging:
  level:
    root: info
    sql: ${SQL_LOG_LEVEL:warn}
    org.hibernate.SQL: ${SQL_LOG_LEVEL:warn}
    org.hibernate.type.descriptor.sql.BasicBinder: ${SQL_LOG_LEVEL:warn}