version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: codin-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-ticketing}
      MYSQL_USER: ${MYSQL_USER:-codin}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-codinpassword}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: codin-ticketing-redis
    ports:
      - "${REDIS_PORT:-6380}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-1234}
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:
