# Spring Boot Configuration
# application.yml
# src/main/resources/**
spring:
  application:
    name: codin-core
  config:
    import: optional:file:./.env[.properties], optional:file:./.env.core[.properties]
  profiles:
    active:
      local, prod
    include: jwt, aws, email, oauth
  servlet:
    multipart:
      max-request-size: ${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE}
      max-file-size: ${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE}
  data:
    redis: # [Redis] 설정
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
    mongodb: # [MongoDB] 설정
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DATABASE}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      authentication-database: ${MONGODB_AUTH_DATABASE:admin}


google:
  firebase:
    project-id: ${GOOGLE_FIREBASE_PROJECT_ID}
    key-path: ${GOOGLE_FIREBASE_KEY_PATH}

server:
  servlet:
    encoding:
      force-response: true
      charset: UTF-8
      enabled: true
  domain: ${CORE_SERVER_DOMAIN}
  forward-headers-strategy: framework
  port: ${CORE_SERVER_PORT}

springdoc:
  api-docs:
    enabled: ${SPRINGDOC_API_DOCS_ENABLED}
  swagger-ui:
    groups-order: DESC
    doc-expansion: list
    tags-sorter: alpha
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true

schedule:
  path: ${SCHEDULE_PATH}
  department:
    cron: ${SCHEDULE_DEPARTMENT_CRON:0 00 4 * * *}
  starinu:
    cron: ${SCHEDULE_STARINU_CRON:0 30 4 * * *}

lecture:
  python:
    path: ${LECTURE_PYTHON_PATH}
  file:
    path: ${LECTURE_FILE_PATH}

logging:
  level:
    org.springframework.security: DEBUG