spring:
  application:
    name: codin-lecture-api
  config:
    import: optional:file:.env[.properties]
  jwt:
    secret: ${SPRING_JWT_SECRET}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

lecture:
  python:
    path: ${PYTHON_PATH:./example}
  file:
    path: ${PYTHON_FILE_PATH:./example}

server:
  port: ${SERVER_PORT}
  domain: ${SERVER_DOMAIN}
  forward-headers-strategy: framework
  feign:
    url: ${SERVER_FEIGN_URL}

logging:
  level:
    root: info
    sql: info
    org.hibernate.sql: info