spring:
  application:
    name: codin-lecture-api
  config:
    import: optional:file:.env.local[.properties]
  jwt:
    secret: ${SPRING_JWT_SECRET}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  elasticsearch:
    uris: ${ELASTICSEARCH_URL:http://localhost:9200}
    indices:
      lectures:
        settings:
          analysis:
            tokenizer:
              nori_tokenizer:
                type: nori_tokenizer
                decompound_mode: mixed
            filter:
              nori_readingform:
                type: nori_readingform
              nori_hanja_readingform:
                type: nori_hanja_readingform
              autocomplete_filter:
                type: edge_ngram
                min_gram: 1
                max_gram: 20
            analyzer:
              nori:
                type: custom
                tokenizer: nori_tokenizer
                filter: [ nori_readingform, nori_hanja_readingform, lowercase ]
              nori_autocomplete:
                type: custom
                tokenizer: nori_tokenizer
                filter: [ nori_readingform, autocomplete_filter, lowercase ]

lecture:
  python:
    path: ${PYTHON_PATH:./example}
  file:
    path: ${PYTHON_FILE_PATH:./example}

server:
  port: ${SERVER_PORT}
  domain: ${SERVER_DOMAIN}
  forward-headers-strategy: framework
  feign:
    url: ${SERVER_FEIGN_URL}

logging:
  level:
    root: info
    sql: debug
    org.hibernate.sql: info