name: deploy CI/CD on branch 'main'
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      # 1. 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. JDK 17 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: '17'

      # 3. 이전 빌드 제거
      - name: Remove old JARs
        run: |
          rm -rf build/libs/*.jar
          rm -rf codin-ticketing-sse/build/libs/*.jar

      # 4. API 모듈 Gradle 빌드
      - name: Build root project
        run: ./gradlew build -x test

      # 5. SSE 모듈 별도 Gradle 빌드
      - name: Build SSE module
        working-directory: codin-ticketing-sse
        run: ./gradlew build -x test

      # 6. Docker Hub Login
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 7. API 이미지 build-push
      - name: Build & Push API image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/codin-ticketing-api:latest

      # 8) SSE 이미지 build-push
      - name: Build & Push SSE image
        uses: docker/build-push-action@v5
        with:
          context: codin-ticketing-sse
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/codin-ticketing-sse:latest

      # 9. 서버에 배포
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          port: ${{ secrets.PORT }}
          script: |
            echo ${{ secrets.PASSWORD }} | sudo -S su -c "  
              docker ps -a
              cd /opt/project/codin-ticketing

              docker pull ${{ secrets.DOCKERHUB_USERNAME }}/codin-ticketing-api:latest
              docker pull ${{ secrets.DOCKERHUB_USERNAME }}/codin-ticketing-sse:latest
  
              docker rm -f codin-ticketing-api || true
              docker rm -f codin-ticketing-sse || true
  
              docker-compose -f ticketing-docker-compose.yml up -d
  
              docker images -f "dangling=true" -q | xargs sudo docker rmi || true
              docker ps -a
            "